/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NameGeneratorGui.java
 *
 * Created on May 17, 2012, 3:12:45 PM
 */
package javanamegenerator2.pkg0;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author Armand
 */
public class NameGeneratorGui extends javax.swing.JFrame {

    private NameGeneratorLogic logic;
    // Some default values
    private final static int SHORT = 3;
    private final static int MEDIUM = 6;
    private final static int LONG = 12;
    private final static int FEW = 10;

    /** Creates new form NameGeneratorGui */
    public NameGeneratorGui() {
        initComponents();
        resetValues();
    }

    private void resetValues() {
        sldr_amount.setValue(FEW);
        sldr_length.setValue(1);
        txt_amount.setText(Integer.toString(FEW));
        txt_length.setText("Medium");
    }

    private int getLength() {
        int length;
        if (txt_length.getText().toLowerCase().equals("short")) {
            length = SHORT;
        } else if (txt_length.getText().toLowerCase().equals("medium")) {
            length = MEDIUM;
        } else if (txt_length.getText().toLowerCase().equals("long")) {
            length = LONG;
        } else {
            try {
                length = Integer.parseInt(txt_length.getText());
            } catch (NumberFormatException nfe) {
                length = MEDIUM;
            }
        }
        return length;
    }

    private int getAmount() {
        int amount;
        try {
            amount = Integer.parseInt(txt_amount.getText());
        } catch (NumberFormatException nfe) {
            amount = FEW;
        }
        return amount;
    }

    private void generateNames() {
        NameGeneratorLogic nameGenLogic = new NameGeneratorLogic(this, getLength(), getAmount());
        Thread logicThread = new Thread(nameGenLogic);
        logicThread.start();
    }

    public void writeName(String name) {
        Document doc = txt_resultsPane.getDocument();
        try {
            doc.insertString(doc.getLength(), name + "\n", null);
        } catch (BadLocationException ex) {
            Logger.getLogger(NameGeneratorGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpFormat = new javax.swing.ButtonGroup();
        lbl_amount = new javax.swing.JLabel();
        sldr_amount = new javax.swing.JSlider();
        lbl_head = new javax.swing.JLabel();
        txt_length = new javax.swing.JTextField();
        sldr_length = new javax.swing.JSlider();
        lbl_length = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_resultsPane = new javax.swing.JTextPane();
        btn_go = new javax.swing.JButton();
        lblFormat = new javax.swing.JLabel();
        rbtnText = new javax.swing.JRadioButton();
        rbtnSqlInsert = new javax.swing.JRadioButton();
        rbtn_custom = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_amount.setText("Amount");

        sldr_amount.setMajorTickSpacing(10);
        sldr_amount.setMinimum(1);
        sldr_amount.setMinorTickSpacing(5);
        sldr_amount.setPaintTicks(true);
        sldr_amount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldr_amountStateChanged(evt);
            }
        });

        lbl_head.setText("Use the sliders or type a custom value in the text fields.");

        sldr_length.setMajorTickSpacing(1);
        sldr_length.setMaximum(2);
        sldr_length.setPaintTicks(true);
        sldr_length.setSnapToTicks(true);
        sldr_length.setValue(1);
        sldr_length.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldr_lengthStateChanged(evt);
            }
        });

        lbl_length.setText("Base length");
        lbl_length.setToolTipText("The base length is not an absolute length, it serves merely as a guide as to the length of the generated names.");

        txt_resultsPane.setEditable(false);
        jScrollPane1.setViewportView(txt_resultsPane);

        btn_go.setText("Go");
        btn_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goActionPerformed(evt);
            }
        });

        lblFormat.setText("Format:");

        btngrpFormat.add(rbtnText);
        rbtnText.setText("Text");

        btngrpFormat.add(rbtnSqlInsert);
        rbtnSqlInsert.setText("SQL Insert");

        rbtn_custom.setText("Custom");

        jMenu1.setText("File");

        jMenuItem1.setText("Generate Letter Relationships");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_head, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_length, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sldr_amount, 0, 0, Short.MAX_VALUE)
                            .addComponent(sldr_length, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_length, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_go))
                            .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(lblFormat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(rbtnSqlInsert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(rbtn_custom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_head, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldr_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_length, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_go, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_length, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sldr_length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFormat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnSqlInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn_custom))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldr_amountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldr_amountStateChanged
        txt_amount.setText(Integer.toString(sldr_amount.getValue()));
    }//GEN-LAST:event_sldr_amountStateChanged

    private void sldr_lengthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldr_lengthStateChanged
        String length;
        switch (sldr_length.getValue()) {
            case 0:
                length = "Short";
                break;
            case 1:
                length = "Medium";
                break;
            default:
                length = "Long";
                break;
        }
        txt_length.setText(length);
    }//GEN-LAST:event_sldr_lengthStateChanged

    private void btn_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goActionPerformed
        txt_resultsPane.setText("");
        generateNames();
    }//GEN-LAST:event_btn_goActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new MarkovRelations().generateMarkovRelations("src/NameData/names.txt");
//        new MarkovRelations().generateMarkovRelations("src/NameData/test.txt");
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the System look and feel
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NameGeneratorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NameGeneratorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NameGeneratorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NameGeneratorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                GuiBean bean = new GuiBean();;
                NameGeneratorGui gui = new NameGeneratorGui();
                gui.setVisible(true);
                gui.setLocationRelativeTo(null);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_go;
    private javax.swing.ButtonGroup btngrpFormat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_head;
    private javax.swing.JLabel lbl_length;
    private javax.swing.JRadioButton rbtnSqlInsert;
    private javax.swing.JRadioButton rbtnText;
    private javax.swing.JRadioButton rbtn_custom;
    private javax.swing.JSlider sldr_amount;
    private javax.swing.JSlider sldr_length;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_length;
    private javax.swing.JTextPane txt_resultsPane;
    // End of variables declaration//GEN-END:variables
}
